### PR TITLE
Add attributes to tunnel to store meta information.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
https://github.com/eclipse/che/issues/16250

### What issues does this PR fix or reference?
Add attributes to tunnel to store meta information.

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by skabashnyuk** [comment]
- what about tests?
- what about docs?
- how it is related to https://github.com/eclipse/che/issues/16250 ?

**Comment by AndrienkoAleksandr** [comment]
> how it is related to eclipse/che#16250 ?

We need to have ability store meta-data information in the tunnel. For issue how it is related to eclipse/che#16250  we need to store token.

**Comment by skabashnyuk** [comment]
- Does this token have any lifetime or it's endless?
- What will happen after application restart/upgrade?

**Comment by AndrienkoAleksandr** [comment]
> Does this token have any lifetime or it's endless?

@sleshchenko ?

**Comment by sleshchenko** [comment]
@skabashnyuk I'm not sure about token's lifetime, but che-machine-exec uses it only during terminal initializing...

> What will happen after application restart/upgrade?

Che-machine-exec loses all websocket connections and users have to provide new token once CloudShell UI is refreshed.

**Review by sleshchenko — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
